### ISSUE TITLE
LiveView - TODO's List

### ISSUE THREAD

**Issue by herminiotorres** [groxio-learning/barquinhos#20]
- [ ] use flash message to give more hints to the player when it needs to pick orientation and ship
- [ ] validate the boundary for the board
- [ ] validate when try to put ship above other ship
- [ ] remove the button after picking the ship on board
- [ ] improves the variable names to tells more about the context/action they have
- [ ] register shots dynamically instead of hardcode
