### ISSUE TITLE
More LiveView ToDo's

### ISSUE THREAD

**Issue by SophieDeBenedetto** [groxio-learning/barquinhos#22]
Some more ToDo items that came out of "Group Attack" (@sophiedebenedetto Mohammad @jacquelineIO @graceinwonderland)

- [ ] Timer optimization (if you don't make an attack in X minutes, the game makes one for you)
- [ ] Thinking about accessibility - should we disable points so that you can't make the same attack twice?
- [ ] Display difference between a hit/miss 

Next time...
- [ ] Integrate PubSub to make attacks _against_ another player
